%% This code concatenates per day the V05B IMERG files in Matlab format
% generated by March Jacob, Rev1: 04/03/2019
% updated by Kyla Drushka on 08/05/2020 to account for the 
%different ranges between CMORPH (0:360) and IMERG (-180:180) longitudes

function ConcatenatingDaily_IMERG_V06B_Rev2(yyyy,mm,dd)

% yyyy = year of the data to process
% dd1 = initial day of the processing data interval
% dd2 = final day of the processing data interval

clc
% dir1=pwd;
% dir1='/disk4/OceanSalinity/RIM/IMERG/Data/GriddedData/PerOrbit';
% dir2='/disk4/OceanSalinity/RIM/IMERG/Data/GriddedData/Daily';
dir1 = 'Z:\OceanSalinity\RIM\IMERG\Data\GriddedData\PerOrbit\V06B';
dir2 = 'Z:\OceanSalinity\RIM\IMERG\Data\GriddedData\Daily';

outdir = [dir2 '/']; % output folder
dir_y = [dir1 '/'];% input folder

for m = 1:size(mm,2)
    
    for d = 1:size(dd,2)
        
        files = dir([dir_y,'IMERG_V06B_30min_quarter_',num2str(yyyy),num2str(mm(m),'%0.2d'),num2str(dd(d),'%0.2d'),'*']);
        im = nan(720,1440,48);
        for k = 1:size(files,1)
        
            name = [dir_y,files(k).name];
            disp(name)
        
            load(name)
            imerg=imerg(:,[721:1440,1:720]);  % shift so lon goes from 0:360 instead of -180:180   
            imerg(imerg<0) = nan; %before <-0.05, it was an idea from J. Boutin to keep 0 rains in averages
            im(:,:,k) = imerg;
            clear imerg;
            
            disp(['done ',num2str(yyyy),num2str(mm,'%0.2d'),num2str(d,'%0.2d'),'_',num2str(k,'%0.2d')])
        
        end
        
        imerg = im;
        
        disp(['done ',num2str(yyyy),num2str(mm,'%0.2d'),num2str(d,'%0.2d')])
        
        nameFile = ['IMERG_V06B_30min_quarter_' num2str(yyyy) num2str(mm,'%0.2d'),num2str(d,'%0.2d')];
        save([outdir nameFile '.mat'], 'imerg')
        
    end
    
    disp(['done ',num2str(yyyy),num2str(mm,'%0.2d')])
    disp('done')
    
end